### ISSUE TITLE
Impossible to create Mini App (Error: ENOENT: no such file or directory, open *\test\apps\server\.env')

### ISSUE THREAD

**Issue by QuentinNev** [gramiojs/create-gramio#100]
When running the command `npm create gramio@latest ./test`, I get this error : 

```
Error: ENOENT: no such file or directory, open 'C:\Users\OnStandBy\Documents\dev\_RaptorLab\Shockwaves\fuck\apps\server\.env'
    at async open (node:internal/fs/promises:638:25)
    at async writeFile (node:internal/fs/promises:1208:14)
    at async C:\Users\OnStandBy\AppData\Local\npm-cache\_npx\fcaf6781abea57d9\node_modules\create-gramio\dist\index.js:207:2197
    at async [run] (C:\Users\OnStandBy\AppData\Local\npm-cache\_npx\fcaf6781abea57d9\node_modules\tasuku\dist\index.cjs:71:8168)
    at async u (C:\Users\OnStandBy\AppData\Local\npm-cache\_npx\fcaf6781abea57d9\node_modules\tasuku\dist\index.cjs:71:8395)
    at async C:\Users\OnStandBy\AppData\Local\npm-cache\_npx\fcaf6781abea57d9\node_modules\create-gramio\dist\index.js:207:1886 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\OnStandBy\\Documents\\dev\\test\\apps\\server\\.env'
}
```

Tested on Windows 10 and Ubuntu 24.10

**Comment by kravetsone** [comment]
> When running the command `npm create gramio@latest ./test`, I get this error :
> 
> ```
> Error: ENOENT: no such file or directory, open 'C:\Users\OnStandBy\Documents\dev\_RaptorLab\Shockwaves\fuck\apps\server\.env'
>     at async open (node:internal/fs/promises:638:25)
>     at async writeFile (node:internal/fs/promises:1208:14)
>     at async C:\Users\OnStandBy\AppData\Local\npm-cache\_npx\fcaf6781abea57d9\node_modules\create-gramio\dist\index.js:207:2197
>     at async [run] (C:\Users\OnStandBy\AppData\Local\npm-cache\_npx\fcaf6781abea57d9\node_modules\tasuku\dist\index.cjs:71:8168)
>     at async u (C:\Users\OnStandBy\AppData\Local\npm-cache\_npx\fcaf6781abea57d9\node_modules\tasuku\dist\index.cjs:71:8395)
>     at async C:\Users\OnStandBy\AppData\Local\npm-cache\_npx\fcaf6781abea57d9\node_modules\create-gramio\dist\index.js:207:1886 {
>   errno: -4058,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: 'C:\\Users\\OnStandBy\\Documents\\dev\\test\\apps\\server\\.env'
> }
> ```
> 
> Tested on Windows 10 and Ubuntu 24.10

oh sorry for the late response

when it caused? what step?

**Comment by TemaSM** [comment]
@kravetsone, hi there!
First of all, I can't help but thank you for all your efforts on various open-source libraries and repositories, including the GramIO framework. It's incredibly valuable that you contribute to the development of the community around Telegram development. Keep it up – you're doing an amazing job 👍 

---

**Issue/question:**

I tried initializing a TMA monorepo using the documentation: https://gramio.dev/tma/#scaffold-monorepo

However, the generated folder structure doesn't look like a monorepo and is missing the directories mentioned in the docs, such as `/apps/bot`, `/apps/mini-app`, `/apps/server`, and the `packages` folder.

<details>
  <summary>Here’s the folder structure I got instead:</summary>

![Image](https://github.com/user-attachments/assets/b7ba360e-c1ac-4ce0-b76a-74ae1351e1f2)
  
</details>

<details>
  <summary>Here’s a screenshot of my answers during `pnpm create gramio@latest .`:</summary>

![Image](https://github.com/user-attachments/assets/1784e6e3-9eb6-4efe-9633-22f199755fe5)
  
</details>

- Notably, during initialization, there was no option to select `App` — only `Bot` was available under `Select type of project:`.
It seems the init tool didn't provide an option to scaffold the full monorepo structure as described in the documentation.
---
Could you please tell me whether I made a mistake somewhere, or is this a mismatch between the documentation and the actual implementation of `create-gramio`?

**Comment by kravetsone** [comment]
> *Also, an interesting observation regarding Developer Experience:
> I selected MySQL as the database to be used with the ORM, and I noticed that the generated docker-compose files included a service for Redis (presumably for the Scenes plugin). However, there was no corresponding service or configuration for MySQL in the docker-compose file.
> 
> I think this could be improved to enhance the developer experience. As an external developer trying to get started by following the documentation step by step, I wasn't able to use GramIO "out of the box" as expected. Including MySQL in the generated setup would make the onboarding process much smoother.

Yes, this is something that needs to be fixed. Currently, the corresponding field is being created in docker-compose only for PostgreSQL
I'll improve it soon.

**Comment by kravetsone** [comment]
> Notably, during initialization, there was no option to select App — only Bot was available under Select type of project:.
> It seems the init tool didn't provide an option to scaffold the full monorepo structure as described in the documentation.

Oh i didnt rememver why i remove project type selection support for non-bun pms

**Comment by kravetsone** [comment]
can u try again? @TemaSM 

@QuentinNev also looks like your issue fixed feels free to reopen

**Comment by TemaSM** [comment]
@kravetsone Thanks for the improvements!

Yesterday, I forked `create-gramio` and found a `filter` condition around the `Select type of project` prompt, [where there was a check](https://github.com/gramiojs/create-gramio/blame/64df1d0520be57004d2758b0b95897da5d00235c/src/index.ts#L126-L128) for `bun`.

I removed that check and tried initializing the project again. Today, I also tested the original `create-gramio` after your recent updates.

Unfortunately, no success so far. The process exits during the initialization step of `elysia` with the following console error:

```
Error: Now supported only bun
    at Object.<anonymous> (create-elysiajs@1.5.0\node_modules\create-elysiajs\dist\index.js:988:37)
```

<details>
  <summary>(full screenshot)</summary>
  
![Image](https://github.com/user-attachments/assets/c5efee20-200f-45a4-9fb9-b0da00fc08cd)

</details>

So, I think it’s necessary to first fix `create-elysia` to work under Node, which would allow it to be used during the initialization of a `Mini App + Bot + Elysia (backend framework) monorepo`.

If I have time, I’ll make the necessary fixes, test them, and submit a PR.

**Comment by kravetsone** [comment]
> [@kravetsone](https://github.com/kravetsone) Thanks for the improvements!
> 
> Yesterday, I forked `create-gramio` and found a `filter` condition around the `Select type of project` prompt, [where there was a check](https://github.com/gramiojs/create-gramio/blame/64df1d0520be57004d2758b0b95897da5d00235c/src/index.ts#L126-L128) for `bun`.
> 
> I removed that check and tried initializing the project again. Today, I also tested the original `create-gramio` after your recent updates.
> 
> Unfortunately, no success so far. The process exits during the initialization step of `elysia` with the following console error:
> 
> ```
> Error: Now supported only bun
>     at Object.<anonymous> (create-elysiajs@1.5.0\node_modules\create-elysiajs\dist\index.js:988:37)
> ```
> 
> (full screenshot)
> So, I think it’s necessary to first fix `create-elysia` to work under Node, which would allow it to be used during the initialization of a `Mini App + Bot + Elysia (backend framework) monorepo`.
> 
> If I have time, I’ll make the necessary fixes, test them, and submit a PR.

uhh yes, elysia has been a bun only framework for a long time. Do you want to use it? With Node.js or Bun? Now the "runtime" is taken based on the package manager

**Comment by TemaSM** [comment]
Currently I prefer to use Node as main JS runtime and `pnpm` as package manager
